apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    tier: frontend
    app: nginx

spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 3
  template:
    metadata:
      name: app-deployment
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
      