apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine
spec:
  replicas: 3
  template:
    metadata:
      name: alpine
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine:latest
