apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  selector:
    app: result
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 8081
    targetPort: 80
    nodePort: 31001
